"""empty message

Revision ID: 17bd2ad0c89a
Revises: 
Create Date: 2019-12-24 22:01:05.015904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bd2ad0c89a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=False),
    sa.Column('user_password', sa.String(length=30), nullable=False),
    sa.Column('user_nickname', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
